spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/dataflowdb?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      connection-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: com.baojie.boot.jpa.strategy.NamingStrategy
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        web: DEBUG